### ISSUE TITLE
Compiler options from extended tsconfig are being ignored

### ISSUE THREAD

**Issue by gablabelle** [Floffah/esbuild-plugin-d.ts#4] opened 2021-06-20 05:53 UTC
In our monorepo, each package has a tsconfig that extends a shared tsconfig located at the root of the yarn workspace. It seems that the compilerOptions from the extended tsconfig are not being taken into consideration.

For example, I had to add `"declarationMap": true,` in order to generate sourcemaps for d.ts files even though the option is enabled in `tsconfig.settings.json`.

```
{
  "extends": "../../tsconfig.settings.json",
  "compilerOptions": {
    "declarationDir": "dist",
    "emitDeclarationOnly": true,
    "declarationMap": true,
    "rootDir": "src"
  },
  "include": ["src"]
}
```

https://github.com/Floffah/esbuild-plugin-d.ts/blob/362490fc4bf9e5165e492a77c97d0956d8858b29/src/plugin.ts#L15

Not a big deal I guess, but simply wanted to point this out.

Thanks for that plugin! ;-)

**Comment by Floffah** [comment] 2021-06-20 09:13
ah yeah this must have been broken when I switched to using conf.conf.compilerOptions because just passing conf.conf makes it not even read the config at all.
to fix this I could check if its there and create a new object which is a spread of the extends properties config and the project config to pick it up

thank you for the issue :)

**Comment by gablabelle** [comment] 2021-06-20 16:47
![Screen Shot 2021-06-20 at 10 17 54](https://user-images.githubusercontent.com/1565793/122681978-ef172a00-d1c4-11eb-814a-20906cabd184.png)

Path resolution seems to be problematic in your 1.0.5 release.

In my case, monorepo root is `/Users/gabriel.labelle/Developer/workjam/workjam-web-next` and extended config is located at `/Users/gabriel.labelle/Developer/workjam/workjam-web-next/tsconfig.settings.json`

The lib is located `/Users/gabriel.labelle/Developer/workjam/workjam-web-next/libs/ui-atoms`.

Hope it helps. Does not hesitate if you need more info.

**Comment by Floffah** [comment] 2021-06-20 19:02
how are you using esbuild in these projects? the plugin relies on working directories

**Comment by gablabelle** [comment] 2021-06-21 03:16
It's a monorepo (yarn) like this one:

https://github.com/gablabelle/next-mesh-apollo-monorepo-example

tsconfig in each packages extend the tsconfig at root of the monorepo.

**Comment by Floffah** [comment] 2021-06-21 08:24
where is esbuild being run though? I suspect its a problem with that so Ill make it configurable for where it checks

**Comment by gablabelle** [comment] 2021-06-21 18:02
It is run in each package folders (`packages/*`).

**Comment by Floffah** [comment] 2021-06-24 21:54
I can't think of a valid fix so I've just added an option to override the config path. Please install the package from the repository (`esbuild-plugin-d.ts@floffah/esbuild-plugin-d.ts`) and add this option and tell me if it works. if this is inconvenient I can continue to look for an issue or if you can think of one feel free to open a pull request

**Comment by Floffah** [comment] 2021-06-24 22:18
fixed in 1.0.6, properly tested this time and definitely works.

**Comment by sachinraja** [comment] 2022-01-25 04:09
Seeing this issue (also with `"declarationMap": true`) in the root `tsconfig.build.json`. Seems to only be reading from the package's `tsconfig.build.json` because it works when I put the option in there.

**Comment by Floffah** [comment] 2022-01-25 09:28
> Seeing this issue (also with `"declarationMap": true`) in the root `tsconfig.build.json`. Seems to only be reading from the package's `tsconfig.build.json` because it works when I put the option in there.

could you provide a reproducible example so i can understand this better?
i have a feeling its a problem with moving to the incremental program/host and may be fixed with the solution to #8

**Comment by Floffah** [comment] 2022-01-27 09:54
> Seeing this issue (also with `"declarationMap": true`) in the root `tsconfig.build.json`. Seems to only be reading from the package's `tsconfig.build.json` because it works when I put the option in there. 

After rereading I have a few ideas as to what this could be

What is the working directory of the process when you run esbuild? If it's the root of the project that'll be the problem as it finds the first one it sees inline with a package.json using a function provided by typescript

**Comment by sachinraja** [comment] 2022-01-28 17:42
Sorry for the delay, [here's a repro](https://github.com/sachinraja/esbuild-plugin-dts-repro). Issue seems to be that I set `declarationDir`, removing that fixes it.

**Comment by Floffah** [comment] 2022-01-28 17:47
alright ill look into this when i get time thank you!

**Comment by Floffah** [comment] 2023-12-11 21:44
If this wasn't fixed before, it should be now. I added tests to account for this use case

**Closed** 2023-12-11 21:43 UTC
Labels: bug, good first issue
